import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Header } from "@/components/Header";
import Banner from "@/components/Banner";
import requests from "api";
import { GetServerSideProps } from "next";
import { Movie } from "types";
import { GenreRow } from "@/components/GenreRow";

interface Props {
  netflixOriginals: Movie[];
  trendingNow: Movie[];
  topRated: Movie[];
  actionMovies: Movie[];
  comedyMovies: Movie[];
  horrorMovies: Movie[];
  romanceMovies: Movie[];
  documentaries: Movie[];
  // products: Product[]
}

export default function Home({
  netflixOriginals,
  actionMovies,
  comedyMovies,
  documentaries,
  horrorMovies,
  romanceMovies,
  topRated,
  trendingNow,
}: Props) {
  console.log(actionMovies);
  return (
    <>
      <Head>
        <title>Home - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* Header */}
      <main className="relative pl-4 pb-24 lg:space-y-24 lg:pl-16 ">
        {/* Banner */}
        <Banner netflixOriginals={netflixOriginals} />
        <h1 className="flex min-h-screen flex-col items-center justify-center py-2">
          Netflix - Home
        </h1>
        <section>
          <GenreRow title="Trending Now" movies={trendingNow} />
          <GenreRow title="Top Rated" movies={topRated} />
          <GenreRow title="Action Thrillers" movies={actionMovies} />
          {/* My List */}
          {/* {list.length > 0 && <Row title="My List" movies={list} />} */}

          <GenreRow title="Comedies" movies={comedyMovies} />
          <GenreRow title="Scary Movies" movies={horrorMovies} />
          <GenreRow title="Romance Movies" movies={romanceMovies} />
          <GenreRow title="Documentaries" movies={documentaries} />
        </section>
      </main>
      {/* Modal */}
    </>
  );
}
export const getServerSideProps: GetServerSideProps = async () => {
  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRated).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
    fetch(requests.fetchDocumentaries).then((res) => res.json()),
  ]);

  return {
    props: {
      netflixOriginals: netflixOriginals.results,
      trendingNow: trendingNow.results,
      topRated: topRated.results,
      actionMovies: actionMovies.results,
      comedyMovies: comedyMovies.results,
      horrorMovies: horrorMovies.results,
      romanceMovies: romanceMovies.results,
      documentaries: documentaries.results,
    },
  };
};
